name: CD

on:
  workflow_dispatch:
  push:
    branches: [ feat/* ]
  pull_request:
    branches:
      - feat/#92-CICD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: set yml
        run: |
          mkdir -p ./build/resources/
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./build/resources/application.yml
          find build

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy to secret
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/resources/application.yml"
          target: "~/wachu-server/build/resources/main"
          strip_components: 3

      - name: copy to embedding
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./data/embedding-data.json"
          target: "~/wachu-server/build/"

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~/wachu-server/build/libs/"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            kill -9 $(ps -ef | grep java | head -n 1 | awk '{print $2}') || true
            export SPRING_CONFIG_LOCATION=~/wachu-server/build/resources/application.yml
            nohup java -Dspring.config.location=~/wachu-server/build/resources/application.yml -jar ~/wachu-server/build/libs/*.jar > ~/wachu-server/build/libs/nohup.out 2>&1 &
