name: CI

on:
  #  push:
  #    branches: [ dev, feat/* ]
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      #application.yml 복사
      - name: set yml
        run: |
          mkdir -p ./src/test/resources/
          echo "${{ secrets.APPLICATION_TEST_YML }}" | base64 --decode > ./src/test/resources/application.yml

      - name: make executable gradlew
        run: chmod +x ./gradlew

      # test 진행
      - name: run unittest
        run: |
          ./gradlew clean test -i --scan

      # 결과 Slack에 전송
      - name: result send slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RESULT_SLACK_CI }} # required
        if: always() # Pick up events even if the job fails or is canceled.
